server:
  port: 8080
spring:
#  config:
#    import:
#     - "application_qa.yml"
#     - "application_prod.yml"
  profiles:
    active:
     - "qa"
  datasource:
    driver-class-name: org.h2.Driver
    password: 1234
    url: jdbc:h2:mem:accountsdb
    username: admin
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
build:
  version: "2.0"
accounts:
  message: "Welcome to ZettaBank accounts related APIs"
  contactDetails:
    name: "Mounika Uppuluru - Developer"
    email: "umounika@zettabank.com"
  onCallSupport:
    - (40) 123-45678
    - (40) 456-13459
